-- Webhook tokens are generated by the database, never supplied by the client.
-- The insert permission on workflow_triggers does not include webhook_token in
-- its column list, so this is the only way one can come into existence.
CREATE OR REPLACE FUNCTION public.set_webhook_token()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.type = 'webhook' THEN
    IF NEW.webhook_token IS NULL THEN
      NEW.webhook_token := encode(gen_random_bytes(24), 'hex');
    END IF;
  ELSE
    -- Changing a trigger away from `webhook` retires its token immediately.
    NEW.webhook_token := NULL;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER workflow_triggers_set_webhook_token
  BEFORE INSERT OR UPDATE ON public.workflow_triggers
  FOR EACH ROW EXECUTE FUNCTION public.set_webhook_token();
